services:
  # Application
  framework.application:
    class: 'Maverick\Application'
    arguments:
      - '@framework.router'
      - '@framework.http.request'

  framework.http.request:
    class: 'Psr\Http\Message\ServerRequestInterface'
    factory: ['GuzzleHttp\Psr7\ServerRequest', 'fromGlobals']

  # Router
  framework.router:
    class: 'Maverick\Http\Router\FastRouteRouter'
    arguments:
      - '@fast_route.dispatcher'
      - '@framework.router.route.collection'

  framework.router.route.collection:
    class: 'Maverick\Http\Router\Route\Collection\Collection'
    configurator: ['@framework.router.route.collection.configurator', 'configure']

  framework.router.route.collection.configurator:
    class: 'Maverick\Http\Router\Route\Collection\Configurator\Configurator'
    arguments:
      - '@framework.router.route.loader'
      - '%router.routes_file%'

  framework.router.route.factory:
    class: 'Maverick\Http\Router\Route\Factory\ContainerAwareFactory'
    arguments:
      - '@service_container'

  framework.router.route.loader:
    class: 'Maverick\Http\Router\Route\Loader\YamlLoader'
    arguments:
      - '@framework.router.route.factory'

  framework.router.dispatcher.utility.collection_processor:
    class: 'Maverick\Http\Router\Dispatcher\Utility\CollectionProcessor'
    arguments:
      - '@framework.router.route.collection'

  # Views
  framework.view.welcome:
    class: 'Maverick\View\WelcomeView'

  framework.view.not_found:
    class: 'Maverick\View\NotFoundView'

  framework.view.not_allowed:
    class: 'Maverick\View\NotAllowedView'

  framework.view.fatal_error:
    class: 'Maverick\View\FatalErrorView'

  # Whoops
  whoops.run:
    class: 'Whoops\Run'
    calls:
      - ['pushHandler', ['@whoops.handler.pretty']]
      - ['pushHandler', ['@framework.handler.http_exception']]

  whoops.handler.pretty:
    class: 'Whoops\Handler\PrettyPageHandler'

  framework.handler.http_exception:
    class: 'Maverick\Handler\HttpExceptionHandler'

  framework.handler.safe_render:
    class: 'Maverick\Handler\SafeRenderHandler'
    arguments:
      - '@framework.view.fatal_error'
    calls:
      - ['addView', [404, '@framework.view.not_found']]
      - ['addView', [405, '@framework.view.not_allowed']]

  # Fast route
  fast_route.cached_dispatcher:
    class: 'FastRoute\Dispatcher'
    factory: 'FastRoute\cachedDispatcher'
    arguments:
      - '@framework.router.dispatcher.utility.collection_processor'
      - {cacheFile: '%router.cache_file%'}

  fast_route.dispatcher:
    alias: 'fast_route.cached_dispatcher'
