parameters:
  router.cache_disabled: false

services:
  # Application
  framework.application:
    class: Framework\Application
    arguments:
      - '@framework.router'
    calls:
      - ['setNotFoundHandler', ['@handler.not_found']]
      - ['setNotAllowedHandler', ['@handler.not_allowed']]
      - ['setGenericErrorHandler', ['@handler.generic']]

  # Router
  framework.router:
    class: Framework\Router\FastRoute
    arguments:
      - '@fast_route.cached_dispatcher'

  framework.router.route.collection:
    class: Framework\Router\Route\Collection\Collection
    configurator: ['@framework.router.route.collection.configurator', 'configure']

  framework.router.route.collection.configurator:
    class: Framework\Router\Route\Collection\Configurator\Configurator
    arguments:
      - '@framework.router.route.loader'
      - '%router.routes_file%'

  framework.router.route.factory:
    class: Framework\Router\Route\Factory\ContainerAwareFactory
    arguments:
      - '@service_container'

  framework.router.route.loader:
    class: Framework\Router\Route\Loader\YamlLoader
    arguments:
      - '@framework.router.route.factory'

  framework.router.dispatcher.utility.collection_processor:
    class: Framework\Router\Dispatcher\Utility\CollectionProcessor
    arguments:
      - '@framework.router.route.collection'

  # Handlers

  handler.not_found:
    class: Framework\Handler\NotFoundHandler

  handler.not_allowed:
    class: Framework\Handler\NotAllowedHandler

  handler.generic:
    class: Framework\Handler\GracefulErrorHandler

  # Fast route
  fast_route.cached_dispatcher:
    class: FastRoute\Dispatcher
    factory: 'FastRoute\cachedDispatcher'
    arguments:
      - '@framework.router.dispatcher.utility.collection_processor'
      - {cacheFile: '%router.cache_file%'}

