services:
  # Application
  framework.application:
    class: Framework\Application
    arguments:
      - @framework.router

  # Router
  framework.router:
    class: Framework\Router\FastRoute
    arguments:
      - '@fast_route.dispatcher'

  framework.router.route.collection:
    class: Framework\Router\Route\Collection\Collection
    configurator: ['@framework.router.route.collection.configurator', 'configure']

  framework.router.route.collection.configurator:
    class: Framework\Router\Route\Collection\Configurator\Configurator
    arguments:
      - '@framework.router.route.loader'
      - '%router.routes_file%'

  framework.router.route.factory:
    class: Framework\Router\Route\Factory\ContainerAwareFactory
    arguments:
      - '@service_container'

  framework.router.route.loader:
    class: Framework\Router\Route\Loader\YamlLoader
    arguments:
      - '@framework.router.route.factory'

  framework.router.dispatcher.utility.collection_processor:
    class: Framework\Router\Dispatcher\Utility\CollectionProcessor
    arguments:
      - '@framework.router.route.collection'

  # Fast route
  fast_route.dispatcher:
    class: FastRoute\Dispatcher
    factory: 'FastRoute\cachedDispatcher'
    arguments:
      - '@framework.router.dispatcher.utility.collection_processor'
      - {cacheFile: '%router.cache_file%', cacheDisabled: '%router.cache_disabled%'}

